security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:      [ROLE_USER, ROLE_OTHER, ROLE_STUDENT, ROLE_PARENT, ROLE_TEACHER, ROLE_COUNSELOR, ROLE_DISTRICT]
        ROLE_SUPER_ADMIN: [ROLE_LGS, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/superadmin, role: ROLE_SUPER_ADMIN }
        - { path: ^/user/lgs, role: ROLE_LGS }
        - { path: ^/user/admin, role: ROLE_ADMIN }
        - { path: ^/user/district, role: ROLE_DISTRICT }
        - { path: ^/user/counselor, role: ROLE_COUNSELOR }
        - { path: ^/user/other, role: ROLE_OTHER }
        - { path: ^/user/teacher, role: ROLE_TEACHER }
        - { path: ^/user/parent, role: ROLE_PARENT }
        - { path: ^/user/student, role: ROLE_STUDENT }
        - { path: ^/user/, role: ROLE_USER }