parameters:
    acme_user.listener.login.class: Acme\UserBundle\EventListener\SecurityListener

services:
    acme_user.listener.login:
        class:        "%acme_user.listener.login.class%"
        tags:
            -  { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
        arguments:    [@router, @security.context, @event_dispatcher]
